export enum TransactionType {
  BOUGHT_VIA_CREDIT_CARD = 'BOUGHT_VIA_CREDIT_CARD',
  RECEIVED_PAYMENT = 'RECEIVED_PAYMENT',
  APPLYING_FOR_JOB = 'APPLYING_FOR_JOB',
  APPLICATION_FEE_REFUNDED = 'APPLICATION_FEE_REFUNDED',
}
