import { Command } from 'nestjs-command';
import { Injectable } from '@nestjs/common';
import { CurrencyService } from 'src/modules/content/currency/services/currency.service';

@Injectable()
export class CurrenciesSeedCommand {
  constructor(private readonly currencyService: CurrencyService) {}

  @Command({
    command: 'seed:currencies',
    describe: 'Seed system currencies',
  })
  async seed() {
    const start = new Date();
    console.log('🚀 Starting seeding of currencies...');
    //=============================================================================================
    const data = [
      {
        id: 'AFN',
        code: 'AFN',
        label: 'Afghan afghani',
        symbol: '؋',
        digitsAfterComma: 2,
      },
      {
        id: 'ALL',
        code: 'ALL',
        label: 'Albanian lek',
        symbol: 'L',
        digitsAfterComma: 2,
      },
      {
        id: 'DZD',
        code: 'DZD',
        label: 'Algerian dinar',
        symbol: 'د.ج',
        digitsAfterComma: 2,
      },
      {
        id: 'AOA',
        code: 'AOA',
        label: 'Angolan kwanza',
        symbol: 'Kz',
        digitsAfterComma: 2,
      },
      {
        id: 'ARS',
        code: 'ARS',
        label: 'Argentine peso',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'AMD',
        code: 'AMD',
        label: 'Armenian dram',
        symbol: '֏',
        digitsAfterComma: 2,
      },
      {
        id: 'AWG',
        code: 'AWG',
        label: 'Aruban florin',
        symbol: 'ƒ',
        digitsAfterComma: 2,
      },
      {
        id: 'AUD',
        code: 'AUD',
        label: 'Australian dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'AZN',
        code: 'AZN',
        label: 'Azerbaijani manat',
        symbol: '₼',
        digitsAfterComma: 2,
      },
      {
        id: 'BSD',
        code: 'BSD',
        label: 'Bahamian dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'BHD',
        code: 'BHD',
        label: 'Bahraini dinar',
        symbol: '.د.ب',
        digitsAfterComma: 2,
      },
      {
        id: 'BDT',
        code: 'BDT',
        label: 'Bangladeshi taka',
        symbol: '৳',
        digitsAfterComma: 2,
      },
      {
        id: 'BBD',
        code: 'BBD',
        label: 'Barbadian dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'BZD',
        code: 'BZD',
        label: 'Belize dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'BMD',
        code: 'BMD',
        label: 'Bermudian dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'BTN',
        code: 'BTN',
        label: 'Bhutanese ngultrum',
        symbol: 'Nu.',
        digitsAfterComma: 2,
      },
      {
        id: 'BOB',
        code: 'BOB',
        label: 'Bolivian boliviano',
        symbol: 'Bs.',
        digitsAfterComma: 2,
      },
      {
        id: 'BAM',
        code: 'BAM',
        label: 'Bosnia and Herzegovina convertible mark',
        symbol: 'KM',
        digitsAfterComma: 2,
      },
      {
        id: 'BWP',
        code: 'BWP',
        label: 'Botswana pula',
        symbol: 'P',
        digitsAfterComma: 2,
      },
      {
        id: 'BRL',
        code: 'BRL',
        label: 'Brazilian real',
        symbol: 'R$',
        digitsAfterComma: 2,
      },
      {
        id: 'GBP',
        code: 'GBP',
        label: 'British pound',
        symbol: '£',
        digitsAfterComma: 2,
      },
      {
        id: 'BND',
        code: 'BND',
        label: 'Brunei dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'BGN',
        code: 'BGN',
        label: 'Bulgarian lev',
        symbol: 'лв',
        digitsAfterComma: 2,
      },
      {
        id: 'MMK',
        code: 'MMK',
        label: 'Burmese kyat',
        symbol: 'Ks',
        digitsAfterComma: 2,
      },
      {
        id: 'BIF',
        code: 'BIF',
        label: 'Burundian franc',
        symbol: 'Fr',
        digitsAfterComma: 2,
      },
      {
        id: 'XPF',
        code: 'XPF',
        label: 'CFP franc',
        symbol: 'Fr',
        digitsAfterComma: 2,
      },
      {
        id: 'KHR',
        code: 'KHR',
        label: 'Cambodian riel',
        symbol: '៛',
        digitsAfterComma: 2,
      },
      {
        id: 'CAD',
        code: 'CAD',
        label: 'Canadian dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'CVE',
        code: 'CVE',
        label: 'Cape Verdean escudo',
        symbol: 'Esc',
        digitsAfterComma: 2,
      },
      {
        id: 'KYD',
        code: 'KYD',
        label: 'Cayman Islands dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'XAF',
        code: 'XAF',
        label: 'Central African CFA franc',
        symbol: 'Fr',
        digitsAfterComma: 2,
      },
      {
        id: 'CLP',
        code: 'CLP',
        label: 'Chilean peso',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'CNY',
        code: 'CNY',
        label: 'Chinese yuan',
        symbol: '¥',
        digitsAfterComma: 2,
      },
      {
        id: 'COP',
        code: 'COP',
        label: 'Colombian peso',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'KMF',
        code: 'KMF',
        label: 'Comorian franc',
        symbol: 'Fr',
        digitsAfterComma: 2,
      },
      {
        id: 'CDF',
        code: 'CDF',
        label: 'Congolese franc',
        symbol: 'Fr',
        digitsAfterComma: 2,
      },
      {
        id: 'CRC',
        code: 'CRC',
        label: 'Costa Rican colón',
        symbol: '₡',
        digitsAfterComma: 2,
      },
      {
        id: 'CUC',
        code: 'CUC',
        label: 'Cuban convertible peso',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'CZK',
        code: 'CZK',
        label: 'Czech koruna',
        symbol: 'Kč',
        digitsAfterComma: 2,
      },
      {
        id: 'DKK',
        code: 'DKK',
        label: 'Danish krone',
        symbol: 'kr',
        digitsAfterComma: 2,
      },
      {
        id: 'DJF',
        code: 'DJF',
        label: 'Djiboutian franc',
        symbol: 'Fr',
        digitsAfterComma: 2,
      },
      {
        id: 'DOP',
        code: 'DOP',
        label: 'Dominican peso',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'XCD',
        code: 'XCD',
        label: 'East Caribbean dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'EGP',
        code: 'EGP',
        label: 'Egyptian pound',
        symbol: '£',
        digitsAfterComma: 2,
      },
      {
        id: 'ERN',
        code: 'ERN',
        label: 'Eritrean nakfa',
        symbol: 'Nfk',
        digitsAfterComma: 2,
      },
      {
        id: 'ETB',
        code: 'ETB',
        label: 'Ethiopian birr',
        symbol: 'Br',
        digitsAfterComma: 2,
      },
      {
        id: 'EUR',
        code: 'EUR',
        label: 'Euro',
        symbol: '€',
        digitsAfterComma: 2,
      },
      {
        id: 'FKP',
        code: 'FKP',
        label: 'Falkland Islands Pound',
        symbol: '£',
        digitsAfterComma: 2,
      },
      {
        id: 'FJD',
        code: 'FJD',
        label: 'Fijian dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'GMD',
        code: 'GMD',
        label: 'Gambian dalasi',
        symbol: 'D',
        digitsAfterComma: 2,
      },
      {
        id: 'GEL',
        code: 'GEL',
        label: 'Georgian Lari',
        symbol: 'ლ',
        digitsAfterComma: 2,
      },
      {
        id: 'GHS',
        code: 'GHS',
        label: 'Ghanaian cedi',
        symbol: '₵',
        digitsAfterComma: 2,
      },
      {
        id: 'GIP',
        code: 'GIP',
        label: 'Gibraltar pound',
        symbol: '£',
        digitsAfterComma: 2,
      },
      {
        id: 'GTQ',
        code: 'GTQ',
        label: 'Guatemalan quetzal',
        symbol: 'Q',
        digitsAfterComma: 2,
      },
      {
        id: 'GNF',
        code: 'GNF',
        label: 'Guinean franc',
        symbol: 'Fr',
        digitsAfterComma: 2,
      },
      {
        id: 'GYD',
        code: 'GYD',
        label: 'Guyanese dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'HTG',
        code: 'HTG',
        label: 'Haitian gourde',
        symbol: 'G',
        digitsAfterComma: 2,
      },
      {
        id: 'HNL',
        code: 'HNL',
        label: 'Honduran lempira',
        symbol: 'L',
        digitsAfterComma: 2,
      },
      {
        id: 'HKD',
        code: 'HKD',
        label: 'Hong Kong dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'HUF',
        code: 'HUF',
        label: 'Hungarian forint',
        symbol: 'Ft',
        digitsAfterComma: 2,
      },
      {
        id: 'ISK',
        code: 'ISK',
        label: 'Icelandic króna',
        symbol: 'kr',
        digitsAfterComma: 2,
      },
      {
        id: 'INR',
        code: 'INR',
        label: 'Indian rupee',
        symbol: '₹',
        digitsAfterComma: 2,
      },
      {
        id: 'IDR',
        code: 'IDR',
        label: 'Indonesian rupiah',
        symbol: 'Rp',
        digitsAfterComma: 2,
      },
      {
        id: 'IRR',
        code: 'IRR',
        label: 'Iranian rial',
        symbol: '﷼',
        digitsAfterComma: 2,
      },
      {
        id: 'IQD',
        code: 'IQD',
        label: 'Iraqi dinar',
        symbol: 'ع.د',
        digitsAfterComma: 2,
      },
      {
        id: 'ILS',
        code: 'ILS',
        label: 'Israeli new shekel',
        symbol: '₪',
        digitsAfterComma: 2,
      },
      {
        id: 'JMD',
        code: 'JMD',
        label: 'Jamaican dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'JPY',
        code: 'JPY',
        label: 'Japanese yen',
        symbol: '¥',
        digitsAfterComma: 2,
      },
      {
        id: 'JOD',
        code: 'JOD',
        label: 'Jordanian dinar',
        symbol: 'د.ا',
        digitsAfterComma: 2,
      },
      {
        id: 'KZT',
        code: 'KZT',
        label: 'Kazakhstani tenge',
        symbol: '₸',
        digitsAfterComma: 2,
      },
      {
        id: 'KES',
        code: 'KES',
        label: 'Kenyan shilling',
        symbol: 'Sh',
        digitsAfterComma: 2,
      },
      {
        id: 'KWD',
        code: 'KWD',
        label: 'Kuwaiti dinar',
        symbol: 'د.ك',
        digitsAfterComma: 2,
      },
      {
        id: 'KGS',
        code: 'KGS',
        label: 'Kyrgyzstani som',
        symbol: 'с',
        digitsAfterComma: 2,
      },
      {
        id: 'LAK',
        code: 'LAK',
        label: 'Lao kip',
        symbol: '₭',
        digitsAfterComma: 2,
      },
      {
        id: 'LBP',
        code: 'LBP',
        label: 'Lebanese pound',
        symbol: 'ل.ل',
        digitsAfterComma: 2,
      },
      {
        id: 'LSL',
        code: 'LSL',
        label: 'Lesotho loti',
        symbol: 'L',
        digitsAfterComma: 2,
      },
      {
        id: 'LRD',
        code: 'LRD',
        label: 'Liberian dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'LYD',
        code: 'LYD',
        label: 'Libyan dinar',
        symbol: 'ل.د',
        digitsAfterComma: 2,
      },
      {
        id: 'MOP',
        code: 'MOP',
        label: 'Macanese pataca',
        symbol: 'P',
        digitsAfterComma: 2,
      },
      {
        id: 'MKD',
        code: 'MKD',
        label: 'Macedonian denar',
        symbol: 'ден',
        digitsAfterComma: 2,
      },
      {
        id: 'MGA',
        code: 'MGA',
        label: 'Malagasy ariary',
        symbol: 'Ar',
        digitsAfterComma: 2,
      },
      {
        id: 'MWK',
        code: 'MWK',
        label: 'Malawian kwacha',
        symbol: 'MK',
        digitsAfterComma: 2,
      },
      {
        id: 'MYR',
        code: 'MYR',
        label: 'Malaysian ringgit',
        symbol: 'RM',
        digitsAfterComma: 2,
      },
      {
        id: 'MVR',
        code: 'MVR',
        label: 'Maldivian rufiyaa',
        symbol: '.ރ',
        digitsAfterComma: 2,
      },
      {
        id: 'MRO',
        code: 'MRO',
        label: 'Mauritanian ouguiya',
        symbol: 'UM',
        digitsAfterComma: 2,
      },
      {
        id: 'MUR',
        code: 'MUR',
        label: 'Mauritian rupee',
        symbol: '₨',
        digitsAfterComma: 2,
      },
      {
        id: 'MXN',
        code: 'MXN',
        label: 'Mexican peso',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'MDL',
        code: 'MDL',
        label: 'Moldovan leu',
        symbol: 'L',
        digitsAfterComma: 2,
      },
      {
        id: 'MNT',
        code: 'MNT',
        label: 'Mongolian tögrög',
        symbol: '₮',
        digitsAfterComma: 2,
      },
      {
        id: 'MAD',
        code: 'MAD',
        label: 'Moroccan dirham',
        symbol: 'د.م.',
        digitsAfterComma: 2,
      },
      {
        id: 'MZN',
        code: 'MZN',
        label: 'Mozambican metical',
        symbol: 'MT',
        digitsAfterComma: 2,
      },
      {
        id: 'NAD',
        code: 'NAD',
        label: 'Namibian dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'NPR',
        code: 'NPR',
        label: 'Nepalese rupee',
        symbol: '₨',
        digitsAfterComma: 2,
      },
      {
        id: 'ANG',
        code: 'ANG',
        label: 'Netherlands Antillean guilder',
        symbol: 'ƒ',
        digitsAfterComma: 2,
      },
      {
        id: 'BYN',
        code: 'BYN',
        label: 'New Belarusian ruble',
        symbol: 'Br',
        digitsAfterComma: 2,
      },
      {
        id: 'TWD',
        code: 'TWD',
        label: 'New Taiwan dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'NZD',
        code: 'NZD',
        label: 'New Zealand dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'NIO',
        code: 'NIO',
        label: 'Nicaraguan córdoba',
        symbol: 'C$',
        digitsAfterComma: 2,
      },
      {
        id: 'NGN',
        code: 'NGN',
        label: 'Nigerian naira',
        symbol: '₦',
        digitsAfterComma: 2,
      },
      {
        id: 'KPW',
        code: 'KPW',
        label: 'North Korean won',
        symbol: '₩',
        digitsAfterComma: 2,
      },
      {
        id: 'NOK',
        code: 'NOK',
        label: 'Norwegian krone',
        symbol: 'kr',
        digitsAfterComma: 2,
      },
      {
        id: 'OMR',
        code: 'OMR',
        label: 'Omani rial',
        symbol: 'ر.ع.',
        digitsAfterComma: 2,
      },
      {
        id: 'PKR',
        code: 'PKR',
        label: 'Pakistani rupee',
        symbol: '₨',
        digitsAfterComma: 2,
      },
      {
        id: 'PAB',
        code: 'PAB',
        label: 'Panamanian balboa',
        symbol: 'B/.',
        digitsAfterComma: 2,
      },
      {
        id: 'PGK',
        code: 'PGK',
        label: 'Papua New Guinean kina',
        symbol: 'K',
        digitsAfterComma: 2,
      },
      {
        id: 'PYG',
        code: 'PYG',
        label: 'Paraguayan guaraní',
        symbol: '₲',
        digitsAfterComma: 2,
      },
      {
        id: 'PEN',
        code: 'PEN',
        label: 'Peruvian sol',
        symbol: 'S/.',
        digitsAfterComma: 2,
      },
      {
        id: 'PHP',
        code: 'PHP',
        label: 'Philippine peso',
        symbol: '₱',
        digitsAfterComma: 2,
      },
      {
        id: 'PLN',
        code: 'PLN',
        label: 'Polish złoty',
        symbol: 'zł',
        digitsAfterComma: 2,
      },
      {
        id: 'QAR',
        code: 'QAR',
        label: 'Qatari riyal',
        symbol: 'ر.ق',
        digitsAfterComma: 2,
      },
      {
        id: 'RON',
        code: 'RON',
        label: 'Romanian leu',
        symbol: 'lei',
        digitsAfterComma: 2,
      },
      {
        id: 'RUB',
        code: 'RUB',
        label: 'Russian ruble',
        symbol: '₽',
        digitsAfterComma: 2,
      },
      {
        id: 'RWF',
        code: 'RWF',
        label: 'Rwandan franc',
        symbol: 'Fr',
        digitsAfterComma: 2,
      },
      {
        id: 'SHP',
        code: 'SHP',
        label: 'Saint Helena pound',
        symbol: '£',
        digitsAfterComma: 2,
      },
      {
        id: 'WST',
        code: 'WST',
        label: 'Samoan tālā',
        symbol: 'T',
        digitsAfterComma: 2,
      },
      {
        id: 'SAR',
        code: 'SAR',
        label: 'Saudi riyal',
        symbol: 'ر.س',
        digitsAfterComma: 2,
      },
      {
        id: 'RSD',
        code: 'RSD',
        label: 'Serbian dinar',
        symbol: 'дин.',
        digitsAfterComma: 2,
      },
      {
        id: 'SCR',
        code: 'SCR',
        label: 'Seychellois rupee',
        symbol: '₨',
        digitsAfterComma: 2,
      },
      {
        id: 'SLL',
        code: 'SLL',
        label: 'Sierra Leonean leone',
        symbol: 'Le',
        digitsAfterComma: 2,
      },
      {
        id: 'SGD',
        code: 'SGD',
        label: 'Singapore dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'SBD',
        code: 'SBD',
        label: 'Solomon Islands dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'SOS',
        code: 'SOS',
        label: 'Somali shilling',
        symbol: 'Sh',
        digitsAfterComma: 2,
      },
      {
        id: 'ZAR',
        code: 'ZAR',
        label: 'South African rand',
        symbol: 'R',
        digitsAfterComma: 2,
      },
      {
        id: 'KRW',
        code: 'KRW',
        label: 'South Korean won',
        symbol: '₩',
        digitsAfterComma: 2,
      },
      {
        id: 'SSP',
        code: 'SSP',
        label: 'South Sudanese pound',
        symbol: '£',
        digitsAfterComma: 2,
      },
      {
        id: 'LKR',
        code: 'LKR',
        label: 'Sri Lankan rupee',
        symbol: 'Rs',
        digitsAfterComma: 2,
      },
      {
        id: 'SDG',
        code: 'SDG',
        label: 'Sudanese pound',
        symbol: 'ج.س.',
        digitsAfterComma: 2,
      },
      {
        id: 'SRD',
        code: 'SRD',
        label: 'Surinamese dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'SZL',
        code: 'SZL',
        label: 'Swazi lilangeni',
        symbol: 'L',
        digitsAfterComma: 2,
      },
      {
        id: 'SEK',
        code: 'SEK',
        label: 'Swedish krona',
        symbol: 'kr',
        digitsAfterComma: 2,
      },
      {
        id: 'CHF',
        code: 'CHF',
        label: 'Swiss franc',
        symbol: 'Fr',
        digitsAfterComma: 2,
      },
      {
        id: 'SYP',
        code: 'SYP',
        label: 'Syrian pound',
        symbol: '£',
        digitsAfterComma: 2,
      },
      {
        id: 'STD',
        code: 'STD',
        label: 'São Tomé and Príncipe dobra',
        symbol: 'Db',
        digitsAfterComma: 2,
      },
      {
        id: 'TJS',
        code: 'TJS',
        label: 'Tajikistani somoni',
        symbol: 'ЅМ',
        digitsAfterComma: 2,
      },
      {
        id: 'TZS',
        code: 'TZS',
        label: 'Tanzanian shilling',
        symbol: 'Sh',
        digitsAfterComma: 2,
      },
      {
        id: 'THB',
        code: 'THB',
        label: 'Thai baht',
        symbol: '฿',
        digitsAfterComma: 2,
      },
      {
        id: 'TOP',
        code: 'TOP',
        label: 'Tongan paʻanga',
        symbol: 'T$',
        digitsAfterComma: 2,
      },
      {
        id: 'TTD',
        code: 'TTD',
        label: 'Trinidad and Tobago dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'TND',
        code: 'TND',
        label: 'Tunisian dinar',
        symbol: 'DT',
        digitsAfterComma: 3,
      },
      {
        id: 'TRY',
        code: 'TRY',
        label: 'Turkish lira',
        symbol: '₺',
        digitsAfterComma: 2,
      },
      {
        id: 'TMT',
        code: 'TMT',
        label: 'Turkmenistan manat',
        symbol: 'm',
        digitsAfterComma: 2,
      },
      {
        id: 'UGX',
        code: 'UGX',
        label: 'Ugandan shilling',
        symbol: 'Sh',
        digitsAfterComma: 2,
      },
      {
        id: 'UAH',
        code: 'UAH',
        label: 'Ukrainian hryvnia',
        symbol: '₴',
        digitsAfterComma: 2,
      },
      {
        id: 'AED',
        code: 'AED',
        label: 'United Arab Emirates dirham',
        symbol: 'د.إ',
        digitsAfterComma: 2,
      },
      {
        id: 'USD',
        code: 'USD',
        label: 'United States dollar',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'UYU',
        code: 'UYU',
        label: 'Uruguayan peso',
        symbol: '$',
        digitsAfterComma: 2,
      },
      {
        id: 'VUV',
        code: 'VUV',
        label: 'Vanuatu vatu',
        symbol: 'Vt',
        digitsAfterComma: 2,
      },
      {
        id: 'VEF',
        code: 'VEF',
        label: 'Venezuelan bolívar',
        symbol: 'Bs S',
        digitsAfterComma: 2,
      },
      {
        id: 'VND',
        code: 'VND',
        label: 'Vietnamese đồng',
        symbol: '₫',
        digitsAfterComma: 2,
      },
      {
        id: 'XOF',
        code: 'XOF',
        label: 'West African CFA franc',
        symbol: 'Fr',
        digitsAfterComma: 2,
      },
      {
        id: 'YER',
        code: 'YER',
        label: 'Yemeni rial',
        symbol: '﷼',
        digitsAfterComma: 2,
      },
      {
        id: 'ZMW',
        code: 'ZMW',
        label: 'Zambian kwacha',
        symbol: 'ZK',
        digitsAfterComma: 2,
      },
    ];

    await this.currencyService.saveMany(data);

    //=============================================================================================
    const end = new Date();
    console.log(
      `✅ Seeding completed in ${end.getTime() - start.getTime()}ms ⏱️`,
    );
  }
}
