export enum JobEvents {
  POST = 'Post',
  CANCEL = 'Cancel',
  CHOOSE_CANDIDATE = 'Choose Candidate',
  REFUSE_CANDIDATE = 'Refuse Candidate',
  REVIEW = 'Review',
  ACCEPT_CANDIDATE = 'Accept Candidate',
  START = 'Start',
  FINISH = 'Finish',
  WORKER_REVIEW = 'Worker Review',
  CLIENT_REVIEW = 'Client Review',
  MARK_SUCCESSFUL = 'Mark Successful',
  HOLD = 'Hold',
  REPOST = 'Repost',
  STOP_HOLD = 'Stop Hold',
  MARK_FAILED = 'Mark Failed',
}
