export enum EventType {
  SIGNIN = 'SIGNIN',
  SIGNUP = 'SIGNUP',
  SIGNOUT = 'SIGNOUT',

  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_ACTIVATE = 'USER_ACTIVATE',
  USER_DEACTIVATE = 'USER_DEACTIVATE',
  USER_APPROVE = 'USER_APPROVE',
  USER_DISAPPROVE = 'USER_DISAPPROVE',

  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_DUPLICATE = 'ROLE_DUPLICATE',

  DEVICE_INFO_CREATE = 'DEVICE_INFO_CREATE',
  DEVICE_INFO_DELETE = 'DEVICE_INFO_DELETE',
}
