export enum EventType {
  SIGNIN = 'SIGNIN',
  SIGNUP = 'SIGNUP',
  SIGNOUT = 'SIGNOUT',

  CLIENT_SIGNIN = 'CLIENT_SIGNIN',
  CLIENT_SIGNUP = 'CLIENT_SIGNUP',

  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_ACTIVATE = 'USER_ACTIVATE',
  USER_DEACTIVATE = 'USER_DEACTIVATE',
  USER_APPROVE = 'USER_APPROVE',
  USER_DISAPPROVE = 'USER_DISAPPROVE',

  PROFILE_UPDATE = 'PROFILE_UPDATE',

  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_DUPLICATE = 'ROLE_DUPLICATE',

  DEVICE_INFO_CREATE = 'DEVICE_INFO_CREATE',
  DEVICE_INFO_DELETE = 'DEVICE_INFO_DELETE',

  BUG_CREATE = 'BUG_CREATE',
  BUG_DELETE = 'BUG_DELETE',

  FEEDBACK_CREATE = 'FEEDBACK_CREATE',
  FEEDBACK_DELETE = 'FEEDBACK_DELETE',

  REGION_CREATE = 'REGION_CREATE',
  REGION_UPDATE = 'REGION_UPDATE',
  REGION_DELETE = 'REGION_DELETE',

  JOB_CREATE = 'JOB_CREATE',
  JOB_UPDATE = 'JOB_UPDATE',
  JOB_DELETE = 'JOB_DELETE',

  JOB_TAG_CREATE = 'JOB_TAG_CREATE',
  JOB_TAG_UPDATE = 'JOB_TAG_UPDATE',
  JOB_TAG_DELETE = 'JOB_TAG_DELETE',
}
