export enum EventType {
  SIGNIN = 'SIGNIN',
  SIGNUP = 'SIGNUP',
  SIGNOUT = 'SIGNOUT',

  CLIENT_SIGNIN = 'CLIENT_SIGNIN',
  CLIENT_SIGNUP = 'CLIENT_SIGNUP',

  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_ACTIVATE = 'USER_ACTIVATE',
  USER_DEACTIVATE = 'USER_DEACTIVATE',
  USER_APPROVE = 'USER_APPROVE',
  USER_DISAPPROVE = 'USER_DISAPPROVE',

  USER_FOLLOW = 'USER_FOLLOW',
  USER_UNFOLLOW = 'USER_UNFOLLOW',

  PROFILE_UPDATE = 'PROFILE_UPDATE',
  EXPERIENCE_UPDATE = 'EXPERIENCE_UPDATE',
  EDUCATION_UPDATE = 'EDUCATION_UPDATE',
  SKILL_UPDATE = 'SKILL_UPDATE',

  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_DUPLICATE = 'ROLE_DUPLICATE',

  DEVICE_INFO_CREATE = 'DEVICE_INFO_CREATE',
  DEVICE_INFO_DELETE = 'DEVICE_INFO_DELETE',

  BUG_CREATE = 'BUG_CREATE',
  BUG_DELETE = 'BUG_DELETE',

  FEEDBACK_CREATE = 'FEEDBACK_CREATE',
  FEEDBACK_DELETE = 'FEEDBACK_DELETE',

  REGION_CREATE = 'REGION_CREATE',
  REGION_UPDATE = 'REGION_UPDATE',
  REGION_DELETE = 'REGION_DELETE',

  JOB_CREATE = 'JOB_CREATE',
  JOB_UPDATE = 'JOB_UPDATE',
  JOB_DELETE = 'JOB_DELETE',

  JOB_TAG_CREATE = 'JOB_TAG_CREATE',
  JOB_TAG_UPDATE = 'JOB_TAG_UPDATE',
  JOB_TAG_DELETE = 'JOB_TAG_DELETE',

  JOB_CATEGORY_CREATE = 'JOB_CATEGORY_CREATE',
  JOB_CATEGORY_UPDATE = 'JOB_CATEGORY_UPDATE',
  JOB_CATEGORY_DELETE = 'JOB_CATEGORY_DELETE',

  JOB_REQUEST_CREATE = 'JOB_REQUEST_CREATE',
  JOB_REQUEST_UPDATE = 'JOB_REQUEST_UPDATE',
  JOB_REQUEST_DELETE = 'JOB_REQUEST_DELETE',
  JOB_REQUEST_APPROVE = 'JOB_REQUEST_APPROVE',
  JOB_REQUEST_REJECT = 'JOB_REQUEST_REJECT',
  JOB_REQUEST_CANCEL = 'JOB_REQUEST_CANCEL',

  JOB_SAVE_CREATE = 'JOB_SAVE_CREATE',
  JOB_SAVE_DELETE = 'JOB_SAVE_DELETE',

  JOB_VIEW_CREATE = 'JOB_VIEW_CREATE',
  JOB_VIEW_DELETE = 'JOB_VIEW_DELETE',

  REF_TYPE_CREATE = 'REF_TYPE_CREATE',
  REF_TYPE_UPDATE = 'REF_TYPE_UPDATE',
  REF_TYPE_DELETE = 'REF_TYPE_DELETE',

  REF_PARAM_CREATE = 'REF_PARAM_CREATE',
  REF_PARAM_UPDATE = 'REF_PARAM_UPDATE',
  REF_PARAM_DELETE = 'REF_PARAM_DELETE',

  //chat
  CONVERSATION_COMPOSE = 'CONVERSATION_COMPOSE',
}
