export enum NotificationType {
  TEST = 'TEST',
  NEW_SIGNIN = 'NEW_SIGNIN',
  NEW_MESSAGE = 'NEW_MESSAGE',
  NEW_JOB_REQUEST = 'NEW_JOB_REQUEST',
  JOB_REQUEST_APPROVED = 'JOB_REQUEST_APPROVED',
  JOB_REQUEST_REJECTED = 'JOB_REQUEST_REJECTED',
}
